import { GroupService } from './GroupService';
import { InfluencerService } from './InfluencerService';
import { ProfileService } from './ProfileService';
import { RestClient } from './RestClient';
import { AuthService } from './AuthService';
import { ConfessionService } from './ConfessionService';
import { CategoryService } from './CategoryService';
import { EmailTemplateService } from './EmailTemplateService';
import { ReportService } from './ReportService';
export * from './AuthService';
export * from './RestClient';
export * from './ProfileService';
export * from './InfluencerService';
export * from './GroupService';
export * from './ConfessionService';
export * from './CategoryService';
export * from './EmailTemplateService';
export * from './ReportService';
export declare const restClient: RestClient;
export declare const authService: AuthService;
export declare const profileService: ProfileService;
export declare const influencerService: InfluencerService;
export declare const groupService: GroupService;
export declare const confessionService: ConfessionService;
export declare const categoryService: CategoryService;
export declare const emailTemplateService: EmailTemplateService;
export declare const reportService: ReportService;
